import type { Kobo, ListingCondition, Timestamp } from './common';

/**
 * A product listing. Top-level collection rather than a subcollection of
 * `stores`, so the public marketplace (SOW §7) can query across every dealer
 * in one indexed read instead of fanning out per store.
 *
 * Store state is denormalized onto each listing (storeApproved, storeVisible,
 * storeSlug, ...) so a public read never needs a rule-time `get()` on the
 * parent store — that would bill an extra document read on every single
 * document evaluated by every query.
 *
 * Collection: `listings/{listingId}`
 */

/**
 * `draft`   — dealer is still editing; invisible to the public; does not
 *             count toward the free-listing limit (SOW §5).
 * `active`  — publicly visible; counts toward the limit. Reachable ONLY via
 *             the publishListing callable, never by direct client write.
 * `archived`— dealer unpublished it; invisible; does not count.
 */
export type ListingStatus = 'draft' | 'active' | 'archived';

export interface ListingImage {
  /** Storage object path: stores/{storeId}/listings/{listingId}/{imageId}.jpg */
  path: string;
  /** Long-lived download URL, resolved at upload time. */
  url: string;
  width: number;
  height: number;
  sizeBytes: number;
}

/** The subset a dealer may write directly. Everything else is backend-owned. */
export interface ListingInput {
  name: string;
  description: string;
  categoryId: string;
  condition: ListingCondition;
  priceKobo: Kobo;
  quantity: number;
  brand: string;
  partNumber: string;
  compatibleMake: string;
  compatibleModel: string;
  images: ListingImage[];
}

export interface Listing extends ListingInput {
  listingId: string;
  /** Immutable after create. Rules reject any update that changes it. */
  storeId: string;

  // --- Backend-controlled below this line ---------------------------------

  status: ListingStatus;

  /**
   * Lowercased prefix tokens over name + brand + partNumber, generated by a
   * Firestore trigger. Deliberately NOT client-writable: a dealer could
   * otherwise stuff tokens to surface for every search term.
   */
  searchTokens: string[];

  /**
   * The whole public predicate collapsed into one indexed boolean:
   *   status === 'active' && storeApproved && storeVisible && !moderation.removed
   *
   * Maintained by a trigger. Exists because Firestore requires a `list` query
   * to carry filters matching the security rule exactly — checking four
   * separate fields would force a 6-field composite index on every
   * marketplace query and a matching 4-way `where` clause on the client.
   */
  publiclyVisible: boolean;

  // Denormalized from the parent store; refreshed by a trigger on store writes.
  storeApproved: boolean;
  storeVisible: boolean;
  storeSlug: string;
  storeBusinessName: string;
  storeState: string;
  storeCity: string;
  storePhone: string;
  storeWhatsapp: string;

  /** SOW §9: admin listing removal. Independent of dealer-controlled status. */
  moderation: {
    removed: boolean;
    removedBy: string | null;
    removedReason: string | null;
    removedAt: Timestamp | null;
  };

  createdAt: Timestamp;
  updatedAt: Timestamp;
  publishedAt: Timestamp | null;
}

/**
 * The single filter every public marketplace and storefront query must carry.
 * It matches the security rule exactly — required, since Firestore rejects a
 * `list` whose constraints don't prove every result satisfies the rule.
 */
export const PUBLIC_LISTING_FILTER = { publiclyVisible: true } as const;

/**
 * Source of truth for that flag. The trigger applies this; nothing else
 * should recompute it independently.
 */
export function computePubliclyVisible(
  listing: Pick<Listing, 'status' | 'storeApproved' | 'storeVisible' | 'moderation'>,
): boolean {
  return (
    listing.status === 'active' &&
    listing.storeApproved &&
    listing.storeVisible &&
    !listing.moderation.removed
  );
}

/** Category taxonomy, admin-managed (SOW §9). Collection: `categories/{id}` */
export interface Category {
  categoryId: string;
  name: string;
  slug: string;
  /** Manual sort order in listing pickers and marketplace nav. */
  order: number;
  active: boolean;
}

/**
 * The seed taxonomy — what `categories/{id}` is populated with.
 *
 * These ids are written into every listing's `categoryId`, so they are load
 * bearing forever: renaming one orphans every listing that used it. Names are
 * display text and an administrator may edit them freely afterwards.
 *
 * Shared rather than duplicated because the marketplace has to filter on
 * exactly what the dealer app offers. It did not, once: the web homepage
 * rendered AUTOMOTIVE_CATEGORIES — which classifies a *business*, not a part —
 * and linked each tile to `/parts?category=<vertical>`. No listing has ever
 * carried `categoryId: 'car'`, so five of those six tiles could only ever
 * return an empty page.
 *
 * Not the source of truth at runtime: the apps read the Firestore collection,
 * so an administrator can add a category without a deploy. This is what the
 * collection is seeded with, and what the marketplace nav offers.
 */
export const LISTING_CATEGORIES = [
  { id: 'engine', name: 'Engine', order: 1 },
  { id: 'brake', name: 'Brake', order: 2 },
  { id: 'suspension', name: 'Suspension', order: 3 },
  { id: 'electrical', name: 'Electrical', order: 4 },
  { id: 'body', name: 'Body', order: 5 },
  { id: 'transmission', name: 'Transmission', order: 6 },
  { id: 'filters', name: 'Filters', order: 7 },
  { id: 'other', name: 'Other', order: 8 },
] as const;

export type ListingCategoryId = (typeof LISTING_CATEGORIES)[number]['id'];
