// Naija Hub Parts — Operated by Lytod Motors Ltd
// RC 1207675 | 50 Olumegbon St, Surulere, Lagos
//
// Stack: Flutter (Android + iOS + Web, one codebase)
//        Hive (offline-first local storage)
//        Firebase Auth + Firestore (single shared database, all platforms)

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure`
import 'services/hive_service.dart';
import 'services/firebase_service.dart';
import 'screens/home_screen.dart';
import 'screens/login_screen.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await HiveService.init();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  FirebaseService.startAutoSync();

  runApp(const NaijaHubPartsApp());
}

class NaijaHubPartsApp extends StatefulWidget {
  const NaijaHubPartsApp({super.key});

  @override
  State<NaijaHubPartsApp> createState() => _NaijaHubPartsAppState();
}

class _NaijaHubPartsAppState extends State<NaijaHubPartsApp> {
  String? _shopId;
  String _shopName = '';

  @override
  void initState() {
    super.initState();
    // Restore session if the dealer already logged in on this device.
    final user = FirebaseAuth.instance.currentUser;
    if (user != null) {
      _shopId = user.uid;
      _shopName = 'My Shop'; // Replace with a value pulled from shops/{shopId} profile doc.
    }
  }

  void _onLoggedIn(String shopId, String shopName) {
    setState(() {
      _shopId = shopId;
      _shopName = shopName;
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Naija Hub Parts',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primaryColor: kOrange,
        colorScheme: ColorScheme.fromSeed(seedColor: kOrange),
        useMaterial3: true,
        inputDecorationTheme: const InputDecorationTheme(
          border: OutlineInputBorder(),
        ),
      ),
      home: _shopId == null
          ? LoginScreen(onLoggedIn: _onLoggedIn)
          : HomeScreen(shopId: _shopId!, shopName: _shopName),
    );
  }
}
